In [40]:
from sqlalchemy import create_engine

source = create_engine('mysql+mysqlconnector://test:test123@db/test')

In [2]:
import pandas as pd

pd.read_sql('select current_date', con=source)

  current_date
0   2021-01-27

In [41]:
df = pd.read_csv('country_vaccinations.csv', 
                 dtype={"total_vaccinations": "Int64", 
                        "people_vaccinated": "Int64", 
                        "people_fully_vaccinated": "Int64", 
                        "daily_vaccinations": "Int64", 
                        "daily_vaccinations_per_million": "Int64"}, encoding='utf-8')
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Argentina,ARG,2020-12-29,700,<NA>,<NA>,NaN,<NA>,0.00,NaN,NaN,<NA>,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
1,Argentina,ARG,2020-12-30,<NA>,<NA>,<NA>,NaN,15656,NaN,NaN,NaN,346,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
2,Argentina,ARG,2020-12-31,32013,<NA>,<NA>,NaN,15656,0.07,NaN,NaN,346,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
3,Argentina,ARG,2021-01-01,<NA>,<NA>,<NA>,NaN,11070,NaN,NaN,NaN,245,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
4,Argentina,ARG,2021-01-02,<NA>,<NA>,<NA>,NaN,8776,NaN,NaN,NaN,194,Sputnik V,Ministry of Health,http://datos.salud.gob.ar/dataset/vacunas-cont...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,Wales,NaN,2021-01-19,176186,175816,370,13989.0,10672,5.59,5.58,0.01,3385,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1423,Wales,NaN,2021-01-20,190831,190435,396,14645.0,11105,6.05,6.04,0.01,3522,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1424,Wales,NaN,2021-01-21,212732,212317,415,21901.0,12318,6.75,6.73,0.01,3907,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1425,Wales,NaN,2021-01-22,241016,240547,469,28284.0,15148,7.64,7.63,0.01,4804,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1426,Wales,NaN,2021-01-23,265054,264538,516,24038.0,17371,8.41,8.39,0.02,5510,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...

In [30]:
df.loc[df.source_website == 'Kuwait', ['source_website']]

Empty DataFrame
Columns: [source_website]
Index: []

In [5]:
df.dtypes

country                                 object
iso_code                                object
date                                    object
total_vaccinations                     float64
people_vaccinated                      float64
people_fully_vaccinated                float64
daily_vaccinations_raw                 float64
daily_vaccinations                     float64
total_vaccinations_per_hundred         float64
people_vaccinated_per_hundred          float64
people_fully_vaccinated_per_hundred    float64
daily_vaccinations_per_million         float64
vaccines                                object
source_name                             object
source_website                          object
dtype: object

In [ ]:
file = open('file.txt', 'r')
file.readlines()
file.close()

with open('file.txt', 'r') as file:
    file.readlines()

fdkjfdkjf

In [39]:
print(pd.io.sql.get_schema(df.reset_index(), 'test.vacinations_per_country', con=source))

CREATE TABLE `test.vacinations_per_country` (
	`index` BIGINT,
	country TEXT,
	iso_code TEXT,
	date TEXT,
	total_vaccinations BIGINT,
	people_vaccinated BIGINT,
	people_fully_vaccinated BIGINT,
	daily_vaccinations_raw FLOAT(53),
	daily_vaccinations BIGINT,
	total_vaccinations_per_hundred FLOAT(53),
	people_vaccinated_per_hundred FLOAT(53),
	people_fully_vaccinated_per_hundred FLOAT(53),
	daily_vaccinations_per_million BIGINT,
	vaccines TEXT,
	source_name TEXT,
	source_website TEXT
)

In [42]:
with source.begin() as transaction:
    transaction.execute('DELETE FROM test.vacinations_per_country')
    df.to_sql('vacinations_per_country', con=transaction, schema='test', if_exists='append', index=False)