In [1]:
from sqlalchemy import create_engine

In [2]:
source = create_engine('mysql+mysqlconnector://test:test123@bi-1_db_1/test')

In [3]:
import pandas as pd

pd.read_sql('select current_date', con=source)

  current_date
0   2021-02-01

In [8]:
import json

In [9]:
with open('unconfirmed-transactions.json') as json_file:
    data = json.load(json_file)

In [39]:
df_input = pd.json_normalize(data['txs'], record_path=['inputs'], meta=['lock_time', 'ver', 'size', 'weight', 'time', 'hash'])
df_input

,sequence,witness,script,prev_out.spent,prev_out.spending_outpoints,prev_out.tx_index,prev_out.type,prev_out.addr,prev_out.value,prev_out.n,prev_out.script,lock_time,ver,size,weight,time,hash
0,4294967295,,483045022100d89d0d108eb3b2215c3a724504d942d5ea...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1KH379RhFTL1dAzq45HkAkt7nU31vJh1ip,3190727,0,76a914c87aad6ddced2ad8e8b257632f14ee9636cbd1b4...,0,1,226,904,1611621833,dd68f3d9b21711243dbd70d3e9914a49bf19e1daa7088b...
1,4294967295,,47304402204944e76b097a8b48a2542f69ae58f324bde3...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1PMf6Yon4GYVTCXeD4rKLTP5QKC52fCHDk,11950578,1,76a914f53ae31b575a268e904bf6ba7ad61acbc73fd713...,0,2,225,900,1611621833,c1dabfa845375b8a07f187522396702a30728cab10d8f2...
2,4294967295,,2200201b460a8741624af2e3cf2f43466b9d9dfdf287b9...,True,"[{'tx_index': 0, 'n': 0}]",0,0,31n7Q4JQLL8xHmsna2yy1AS3JPe3KKpkTd,30949986,1,a91400f6a64b8936dc26bb6921388578937bfcff633e87,0,1,371,821,1611621833,ee3796f7c2c07fca9b48d04e9ec71becb24f621965b119...
3,4294967295,,473044022062e277eea5c8ccb5d4c3f5a6ae23082de820...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1JQttqZ71TYREWkBEHjZqLRzxC6Bcvb4ih,1206555,1,76a914beff062f6aba9a3e906f1e729747dc0a08ced10b...,0,1,223,892,1611621833,c28cb5b54db80ace84ec926dc72f1bb4db53b2d30a6f18...
4,4294967295,,4830450221008d08197dafe1d3a58fe3743363fade8eb4...,True,"[{'tx_index': 0, 'n': 0}]",0,0,14x8G9zJ8Em4Zj74t6GEbuaNf9yPBNR4hY,1141071,1,76a9142b555111612920d115cee985c31eebe57a45cf70...,0,1,226,904,1611621832,83fe83d4c709b54694686c0170d50d01f6c05d36ad7a84...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,4294967295,,,True,"[{'tx_index': 0, 'n': 0}]",0,0,NaN,12970000,2,00202439cb173e0826102aad636d65a9b439bc50f2bb35...,0,1,2127,4110,1611621822,6a986583a0d757df3d0584c48282da71924b17003b603c...
134,4294967295,,,True,"[{'tx_index': 0, 'n': 0}]",0,0,NaN,12980000,1,0020c063ae83925d9ab40903fb9dcfd9738545d11fb85d...,0,1,2127,4110,1611621822,6a986583a0d757df3d0584c48282da71924b17003b603c...
135,4294967295,,483045022100e907fdebe899194155ca5d619c8a0c3fde...,True,"[{'tx_index': 0, 'n': 0}]",0,0,18nQqaTTEmJu98AtiKt4B8xxxPK5DuR2Ct,925630,56,76a914555f7f516cd535ad72debc7ffcf8794380979c09...,0,2,192,768,1611621821,d9f1bc31562e168256862a91abcd15679ea705e1db29e6...
136,4294967295,,473044022072458c152a3675a629117c504d824493e55a...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1982XW9Rpwx9wxbdf7WE1Kc5t72zn2wnTm,1086700,6,76a91459153117775497af406dfd1c0affbfbb1069b172...,0,1,337,1348,1611621822,26107b685c3cc29fdb2f3be2df67cbaf910f930f33f13b...
137,4294967295,,483045022100cf8318f4a29ec7352dccec0b9c4d2d59fe...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1GSBLL5gZmNQyGePZYha5cpUP1NbPadDBD,2108858,0,76a914a94ce95cb7546efd7c978e5310bb46d2843ecd31...,0,1,337,1348,1611621822,26107b685c3cc29fdb2f3be2df67cbaf910f930f33f13b...

In [20]:
df_out = pd.json_normalize(data['txs'], record_path=['out'], meta=['lock_time', 'ver', 'size', 'weight', 'time', 'hash'])
df_out

,spent,tx_index,type,addr,value,n,script,spending_outpoints,lock_time,ver,size,weight,time,hash
0,False,0,0,1N6QEACzeKMPD7hqnFdtncKmvGYAa5h8pE,409558,0,76a914e7601c2ea84ed2be9a250ee2705add9b8bc03f11...,NaN,0,1,226,904,1611621833,dd68f3d9b21711243dbd70d3e9914a49bf19e1daa7088b...
1,False,0,0,12zq7Q9LYgNijXwU3JQE3qVFBuKQej8Z22,2762422,1,76a91415e7feff708bffff9aa7f89b2a3a86a6fc2bc5ae...,NaN,0,1,226,904,1611621833,dd68f3d9b21711243dbd70d3e9914a49bf19e1daa7088b...
2,False,0,0,1DY1gf8ntkxhb1LQnheeJK8eVVQSyghhj6,4493525,0,76a914897ef998b54098c6182da38d2e62c9794225eb48...,NaN,0,2,225,900,1611621833,c1dabfa845375b8a07f187522396702a30728cab10d8f2...
3,False,0,0,1PMf6Yon4GYVTCXeD4rKLTP5QKC52fCHDk,7401553,1,76a914f53ae31b575a268e904bf6ba7ad61acbc73fd713...,NaN,0,2,225,900,1611621833,c1dabfa845375b8a07f187522396702a30728cab10d8f2...
4,False,0,0,3ArxWYVsM8miYG2ySvdGnxd1yKSMK9BFGa,230137,0,a914649a7125c80421c5315584e38996c122c964864087,NaN,0,1,371,821,1611621833,ee3796f7c2c07fca9b48d04e9ec71becb24f621965b119...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,False,0,0,NaN,5498345,0,0020f37eec4f36a96b9c6d00c0b56f2436cf02735d2586...,NaN,0,1,2127,4110,1611621822,6a986583a0d757df3d0584c48282da71924b17003b603c...
117,False,0,0,NaN,13020000,1,00202d0a39578152300a2ed78758335bbd25658daaf1cc...,NaN,0,1,2127,4110,1611621822,6a986583a0d757df3d0584c48282da71924b17003b603c...
118,False,0,0,36yvFsj7UUxQusZGkK4QKfXVQp9UY3nNKi,150000000,2,a9143a0af84ea40b1f39c38d0e4d403d984b5d363e6f87,NaN,0,1,2127,4110,1611621822,6a986583a0d757df3d0584c48282da71924b17003b603c...
119,False,0,0,18geGJirFtn3czbVr7SrHQAQsBe5N53ciZ,902328,0,76a9145448359641e531c23cd4cc699cf15e063a03d7ed...,NaN,0,2,192,768,1611621821,d9f1bc31562e168256862a91abcd15679ea705e1db29e6...
120,False,0,0,3Kc7BMnbWevbj2ysknCssWPNDKvV4eQw8T,3187330,0,a914c4849241eb42fc24717594349b916b286bb271cb87,NaN,0,1,337,1348,1611621822,26107b685c3cc29fdb2f3be2df67cbaf910f930f33f13b...

In [73]:
df_input['prev_out.spending_outpoints'] = df_input['prev_out.spending_outpoints'].astype(str)

In [74]:
df_final = pd.merge(
    df_input,
    df_out,
    how="inner",
    on="hash",
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None,
)

df_final

,sequence,witness,script_x,prev_out.spent,prev_out.spending_outpoints,prev_out.tx_index,prev_out.type,prev_out.addr,prev_out.value,prev_out.n,prev_out.script,lock_time_x,ver_x,size_x,weight_x,time_x,hash,spent,tx_index,type,addr,value,n,script_y,spending_outpoints,lock_time_y,ver_y,size_y,weight_y,time_y
0,4294967295,30440220661ec41bc3a13720b274d290a079e46ed99e98...,16001442cff734190b903eb7c6a05252e86497ce0874bc,True,"[{'tx_index': 0, 'n': 0}]",0,0,3P9ZcMNUrXeJx5pkxKrTE9wViTy5XxYW3z,139763,1,a914eb5fe82a7f26be57d31d82240824765d2d4d70fd87,0,1,247,661,1611621829,10d0d4f4e6cb0949b53a8d4660281c60a003f6b4dd29cc...,False,0,0,3ETLCX46FQyons1CsGC8x1xXsWtVvziZhi,135040,0,a9148c031139d73fc5fe574f672f833182331132d49d87,NaN,0,1,247,661,1611621829
1,4294967295,30440220661ec41bc3a13720b274d290a079e46ed99e98...,16001442cff734190b903eb7c6a05252e86497ce0874bc,True,"[{'tx_index': 0, 'n': 0}]",0,0,3P9ZcMNUrXeJx5pkxKrTE9wViTy5XxYW3z,139763,1,a914eb5fe82a7f26be57d31d82240824765d2d4d70fd87,0,1,247,661,1611621829,10d0d4f4e6cb0949b53a8d4660281c60a003f6b4dd29cc...,False,0,0,3JaUHGkhP3DBudsAYhCA7YRUbFepyTYaj3,1093,1,a914b93d3a87bb83766a26426b0ddd31e2a8fb8b49d887,NaN,0,1,247,661,1611621829
2,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,NaN,0,0,6a4c5058325b52f681025f1de979733118a3c899ce882c...,NaN,0,1,351,1404,1611621823
3,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,1111111111111111111114oLvT2,12500,1,76a9140000000000000000000000000000000000000000...,NaN,0,1,351,1404,1611621823
4,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,1111111111111111111114oLvT2,12500,2,76a9140000000000000000000000000000000000000000...,NaN,0,1,351,1404,1611621823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,4294967295,,220020053218fc9a62474d01dcf27ea09f0a4f78962a01...,True,"[{'tx_index': 0, 'n': 0}]",0,0,33PSFU3hj7HG5QDHMbgZ5EhMMK3fpefQeY,76800,39,a914129d121fe0fb7e9d7c4fb85a4a71ec38c387554b87,0,1,1782,4089,1611621823,fda9ef0ea98cb888ff14f8fc6c18e6f6a5c7fa7d3596ff...,False,0,0,3Ldy8VJmkpnEqg7LTkPWQjJUJHB9fEwxhY,664733,1,a914cfd6cf45497c7ee9845fe1b6172ae18f442b152387,NaN,0,1,1782,4089,1611621823
340,4294967295,,22002056a23356dc2ac8094d3bc10ed4918a15f95b777e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,3MjKKjAdYHtXUmsRCCWVXbUDhjGxuL47q5,123122,4,a914dbd1df45c43c206bbbd2f7a60186a20879854abf87,0,1,1782,4089,1611621823,fda9ef0ea98cb888ff14f8fc6c18e6f6a5c7fa7d3596ff...,False,0,0,NaN,52885,0,0020b2385e1390ac4dd35abb946668a8fe439b327b1179...,NaN,0,1,1782,4089,1611621823
341,4294967295,,22002056a23356dc2ac8094d3bc10ed4918a15f95b777e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,3MjKKjAdYHtXUmsRCCWVXbUDhjGxuL47q5,123122,4,a914dbd1df45c43c206bbbd2f7a60186a20879854abf87,0,1,1782,4089,1611621823,fda9ef0ea98cb888ff14f8fc6c18e6f6a5c7fa7d3596ff...,False,0,0,3Ldy8VJmkpnEqg7LTkPWQjJUJHB9fEwxhY,664733,1,a914cfd6cf45497c7ee9845fe1b6172ae18f442b152387,NaN,0,1,1782,4089,1611621823
342,4294967295,,22002026c774106ea9ec74abc19d1b1f33033a39d576b2...,True,"[{'tx_index': 0, 'n': 0}]",0,0,3997TJBdZTLzGhWvmdB1LE7eNeAkyKuakr,26157,15,a91451b84fd86f73051998d8cff38cee5be99c83992387,0,1,1782,4089,1611621823,fda9ef0ea98cb888ff14f8fc6c18e6f6a5c7fa7d3596ff...,False,0,0,NaN,52885,0,0020b2385e1390ac4dd35abb946668a8fe439b327b1179...,NaN,0,1,1782,4089,1611621823
343,4294967295,,22002026c774106ea9ec74abc19d1b1f33033a39d576b2...,True,"[{'tx_index': 0, 'n': 0}]",0,0,3997TJBdZTLzGhWvmdB1LE7eNeAkyKuakr,26157,15,a91451b84fd86f73051998d8cff38cee5be99c83992387,0,1,1782,4089,1611621823,fda9ef0ea98cb888ff14f8fc6c18e6f6a5c7fa7d3596ff...,False,0,0,3Ldy8VJmkpnEqg7LTkPWQjJUJHB9fEwxhY,664733,1,a914cfd6cf45497c7ee9845fe1b6172ae18f442b152387,NaN,0,1,1782,4089,1611621823

In [75]:
pd.set_option('display.max_columns', None)
df_final.head()

,sequence,witness,script_x,prev_out.spent,prev_out.spending_outpoints,prev_out.tx_index,prev_out.type,prev_out.addr,prev_out.value,prev_out.n,prev_out.script,lock_time_x,ver_x,size_x,weight_x,time_x,hash,spent,tx_index,type,addr,value,n,script_y,spending_outpoints,lock_time_y,ver_y,size_y,weight_y,time_y
0,4294967295,30440220661ec41bc3a13720b274d290a079e46ed99e98...,16001442cff734190b903eb7c6a05252e86497ce0874bc,True,"[{'tx_index': 0, 'n': 0}]",0,0,3P9ZcMNUrXeJx5pkxKrTE9wViTy5XxYW3z,139763,1,a914eb5fe82a7f26be57d31d82240824765d2d4d70fd87,0,1,247,661,1611621829,10d0d4f4e6cb0949b53a8d4660281c60a003f6b4dd29cc...,False,0,0,3ETLCX46FQyons1CsGC8x1xXsWtVvziZhi,135040,0,a9148c031139d73fc5fe574f672f833182331132d49d87,NaN,0,1,247,661,1611621829
1,4294967295,30440220661ec41bc3a13720b274d290a079e46ed99e98...,16001442cff734190b903eb7c6a05252e86497ce0874bc,True,"[{'tx_index': 0, 'n': 0}]",0,0,3P9ZcMNUrXeJx5pkxKrTE9wViTy5XxYW3z,139763,1,a914eb5fe82a7f26be57d31d82240824765d2d4d70fd87,0,1,247,661,1611621829,10d0d4f4e6cb0949b53a8d4660281c60a003f6b4dd29cc...,False,0,0,3JaUHGkhP3DBudsAYhCA7YRUbFepyTYaj3,1093,1,a914b93d3a87bb83766a26426b0ddd31e2a8fb8b49d887,NaN,0,1,247,661,1611621829
2,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,NaN,0,0,6a4c5058325b52f681025f1de979733118a3c899ce882c...,NaN,0,1,351,1404,1611621823
3,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,1111111111111111111114oLvT2,12500,1,76a9140000000000000000000000000000000000000000...,NaN,0,1,351,1404,1611621823
4,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,1111111111111111111114oLvT2,12500,2,76a9140000000000000000000000000000000000000000...,NaN,0,1,351,1404,1611621823

In [76]:
df_final.head()

,sequence,witness,script_x,prev_out.spent,prev_out.spending_outpoints,prev_out.tx_index,prev_out.type,prev_out.addr,prev_out.value,prev_out.n,prev_out.script,lock_time_x,ver_x,size_x,weight_x,time_x,hash,spent,tx_index,type,addr,value,n,script_y,spending_outpoints,lock_time_y,ver_y,size_y,weight_y,time_y
0,4294967295,30440220661ec41bc3a13720b274d290a079e46ed99e98...,16001442cff734190b903eb7c6a05252e86497ce0874bc,True,"[{'tx_index': 0, 'n': 0}]",0,0,3P9ZcMNUrXeJx5pkxKrTE9wViTy5XxYW3z,139763,1,a914eb5fe82a7f26be57d31d82240824765d2d4d70fd87,0,1,247,661,1611621829,10d0d4f4e6cb0949b53a8d4660281c60a003f6b4dd29cc...,False,0,0,3ETLCX46FQyons1CsGC8x1xXsWtVvziZhi,135040,0,a9148c031139d73fc5fe574f672f833182331132d49d87,NaN,0,1,247,661,1611621829
1,4294967295,30440220661ec41bc3a13720b274d290a079e46ed99e98...,16001442cff734190b903eb7c6a05252e86497ce0874bc,True,"[{'tx_index': 0, 'n': 0}]",0,0,3P9ZcMNUrXeJx5pkxKrTE9wViTy5XxYW3z,139763,1,a914eb5fe82a7f26be57d31d82240824765d2d4d70fd87,0,1,247,661,1611621829,10d0d4f4e6cb0949b53a8d4660281c60a003f6b4dd29cc...,False,0,0,3JaUHGkhP3DBudsAYhCA7YRUbFepyTYaj3,1093,1,a914b93d3a87bb83766a26426b0ddd31e2a8fb8b49d887,NaN,0,1,247,661,1611621829
2,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,NaN,0,0,6a4c5058325b52f681025f1de979733118a3c899ce882c...,NaN,0,1,351,1404,1611621823
3,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,1111111111111111111114oLvT2,12500,1,76a9140000000000000000000000000000000000000000...,NaN,0,1,351,1404,1611621823
4,4294967293,,47304402204c8d4e817144d2315a9c3be04dff21fb124e...,True,"[{'tx_index': 0, 'n': 0}]",0,0,1NgC6FnQtc7yarssHm1qJw6tRyABmKBdt4,3069514,3,76a914edc41f3741a491aeac3407ec2d5b3708ec8b705b...,0,1,351,1404,1611621823,14a55560ef71e994c7eaa74eb0a1c36425fec092615e7b...,False,0,0,1111111111111111111114oLvT2,12500,2,76a9140000000000000000000000000000000000000000...,NaN,0,1,351,1404,1611621823

In [77]:
print(pd.io.sql.get_schema(df_final.reset_index(), 'test.unconfirmed_transactions', con=source))

CREATE TABLE `test.unconfirmed_transactions` (
	`index` BIGINT,
	sequence BIGINT,
	witness TEXT,
	script_x TEXT,
	`prev_out.spent` BOOL,
	`prev_out.spending_outpoints` TEXT,
	`prev_out.tx_index` BIGINT,
	`prev_out.type` BIGINT,
	`prev_out.addr` TEXT,
	`prev_out.value` BIGINT,
	`prev_out.n` BIGINT,
	`prev_out.script` TEXT,
	lock_time_x BIGINT,
	ver_x BIGINT,
	size_x BIGINT,
	weight_x BIGINT,
	time_x BIGINT,
	hash TEXT,
	spent BOOL,
	tx_index BIGINT,
	type BIGINT,
	addr TEXT,
	value BIGINT,
	n BIGINT,
	script_y TEXT,
	spending_outpoints TEXT,
	lock_time_y BIGINT,
	ver_y BIGINT,
	size_y BIGINT,
	weight_y BIGINT,
	time_y BIGINT,
	CHECK (`prev_out.spent` IN (0, 1)),
	CHECK (spent IN (0, 1))
)